feat: add lazy loading to images
jsanahuja/InstagramFeed pull request #30
Opened 2020-06-19 16:00 UTC by tavelli

use native web lazy load attribute to optionally enable lazy loading all images for better performance

https://web.dev/native-lazy-loading/

2020-06-19 21:10 UTC, jsanahuja requested changes
Any new functionality must be documented in the docs (index.html) and included at least in the first example.
Also, next time follow CONTRIBUTING.md because you may do changes or add functionality that are not for the convenience of everyone and need to be discused.
If you want you can also send a PR with this new functionality to https://github.com/jsanahuja/jquery.instagramFeed

2020-06-21 01:19 UTC, tavelli commented
hi! updated docs, version number and generated new build. let me know if there is anything else thats needed. i think it will be useful for everyone, might even be worth turning on be default for the good of web performance :)

2020-06-21 02:24 UTC, jsanahuja approved these changes

2020-06-21 02:29 UTC, jsanahuja commented
Thank you!

2020-06-21 02:30 UTC, merged